color:
  saturation: 0.6774194
  brandStrength: 0.3476703
  rhythmicContrast: 0.8064516
  brandColors:
    - '#200116'
    - '#FCFCFC'
    - '#C7A291'
    - '#936D65'
    - '#643942'
  lightness: 0.6827957
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 1
typography_spectrum: 0.8154122
name: 'Bowtie '
